### ISSUE TITLE
Study plan.

### ISSUE THREAD

**Issue by abhi18av** [Mxrcon/Nextflow#1]
Oi @Mxrcon , vamos fazer uma study plan?

**Comment by Mxrcon** [comment]
Seria ótimo! Por conta da faculdade estou tendo dificuldade em conciliar os estudos de nextflow com as tarefas

**Comment by abhi18av** [comment]
Não é uma problema meu amigo, mas não pare :) 

A proxima recurso deve ser isto
https://seqera.io/training/

**Comment by Mxrcon** [comment]
Vou utilizá-lo :)) obrigado
